name: Deploy Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository content
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Use a compatible Ruby version
          bundler-cache: true # Cache dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      # Build the Jekyll site
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
